version: "3.6"
services:
  zillionare:
    build:
      context: .
      args:
        PYPI_INDEX_URL: ${PYPI_INDEX_URL:-https://mirrors.aliyun.com/pypi/simple/}
        # PYPI_INDEX_URL: ${PYPI_INDEX_URL:-https://mirrors.cloud.tencent.com/pypi/simple}
    container_name: zillionare
    image: zillionare:${VERSION:-DEV_BUILD}
    depends_on:
      - postgres
      - redis
    ports:
      - "3181"
      - "3180"
      - "${NOTEBOOK_PORT:-8888}:8888"
    stdin_open: true
    tty: true
    
    working_dir: /apps
    environment:
      - __cfg4py_server_role__
      - INIT_BARS_MONTHS=${INIT_BARS_MONTHS:-1}
      - JQ_ACCOUNT
      - JQ_PASSWORD
      - POSTGRES_USER=${POSTGRES_USER:-zillionare}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-123456}
      - POSTGRES_DB=${POSTGRES_DB:-zillionare}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_ENABLED=${POSTGRES_ENABLED:-true}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    volumes:
      - /Users/lkk/data/tutorial:/tutorial
  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports: 
      - 6379:6379
    command: sh -c 'redis-server --appendonly yes'
  postgres:
    image: postgres:10
    container_name: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-zillionare}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-123456}
      - POSTGRES_DB=${POSTGRES_DB:-zillionare}
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d
